import type { WhitelabelConfig, User, Contact, Deal, Team, TeamStats, Competition } from "./types"

// Mock whitelabel configurations
export const mockWhitelabels: WhitelabelConfig[] = [
  {
    id: "wl-1",
    name: "Acme Corp CRM",
    brandColor: "#3b82f6",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "wl-2",
    name: "TechStart CRM",
    brandColor: "#10b981",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
]

// Mock users
export const mockUsers: User[] = [
  {
    id: "user-1",
    email: "admin@acme.com",
    name: "John Admin",
    role: "admin",
    whitelabelId: "wl-1",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "user-2",
    email: "sales@acme.com",
    name: "Jane Sales",
    role: "user",
    whitelabelId: "wl-1",
    createdAt: new Date("2024-01-02"),
    updatedAt: new Date("2024-01-02"),
  },
  {
    id: "user-3",
    email: "admin@techstart.com",
    name: "Mike Admin",
    role: "admin",
    whitelabelId: "wl-2",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
]

// Mock contacts
export const mockContacts: Contact[] = [
  {
    id: "contact-1",
    name: "Alice Johnson",
    email: "alice@example.com",
    phone: "+1-555-0123",
    company: "Example Inc",
    status: "novo-lead",
    whitelabelId: "wl-1",
    assignedTo: "user-2",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "contact-2",
    name: "Bob Smith",
    email: "bob@demo.com",
    phone: "+1-555-0456",
    company: "Demo Corp",
    status: "em-contato",
    whitelabelId: "wl-1",
    assignedTo: "user-2",
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-12"),
  },
  {
    id: "contact-3",
    name: "Carol Davis",
    email: "carol@startup.com",
    phone: "+1-555-0789",
    company: "Startup LLC",
    status: "fechado",
    whitelabelId: "wl-2",
    assignedTo: "user-3",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "contact-4",
    name: "David Wilson",
    email: "david@tech.com",
    phone: "+1-555-0321",
    company: "Tech Solutions",
    status: "reuniao",
    whitelabelId: "wl-1",
    assignedTo: "user-2",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "contact-5",
    name: "Eva Martinez",
    email: "eva@business.com",
    phone: "+1-555-0654",
    company: "Business Corp",
    status: "em-negociacao",
    whitelabelId: "wl-1",
    assignedTo: "user-4",
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-18"),
  },
  {
    id: "contact-6",
    name: "Frank Brown",
    email: "frank@lost.com",
    phone: "+1-555-0987",
    company: "Lost Opportunity",
    status: "perdido",
    whitelabelId: "wl-1",
    assignedTo: "user-5",
    createdAt: new Date("2024-01-22"),
    updatedAt: new Date("2024-01-22"),
  },
  {
    id: "contact-7",
    name: "Grace Lee",
    email: "grace@newlead.com",
    phone: "+1-555-0147",
    company: "New Lead Inc",
    status: "novo-lead",
    whitelabelId: "wl-1",
    assignedTo: "user-6",
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25"),
  },
  {
    id: "contact-8",
    name: "Henry Kim",
    email: "henry@contact.com",
    phone: "+1-555-0258",
    company: "Contact Corp",
    status: "em-contato",
    whitelabelId: "wl-1",
    assignedTo: "user-2",
    createdAt: new Date("2024-01-28"),
    updatedAt: new Date("2024-01-28"),
  },
]

// Mock deals
export const mockDeals: Deal[] = [
  {
    id: "deal-1",
    title: "Enterprise Software License",
    value: 50000,
    stage: "proposal",
    contactId: "contact-1",
    whitelabelId: "wl-1",
    assignedTo: "user-2",
    expectedCloseDate: new Date("2024-03-15"),
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-25"),
  },
  {
    id: "deal-2",
    title: "Consulting Services",
    value: 25000,
    stage: "negotiation",
    contactId: "contact-2",
    whitelabelId: "wl-1",
    assignedTo: "user-2",
    expectedCloseDate: new Date("2024-02-28"),
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "deal-3",
    title: "SaaS Subscription",
    value: 12000,
    stage: "closed-won",
    contactId: "contact-3",
    whitelabelId: "wl-2",
    assignedTo: "user-3",
    expectedCloseDate: new Date("2024-01-25"),
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-25"),
  },
]

// Mock teams
export const mockTeams: Team[] = [
  {
    id: "team-1",
    name: "Águias de Vendas",
    description: "Equipe focada em grandes contas empresariais",
    color: "#3b82f6",
    leaderId: "user-2",
    memberIds: ["user-2", "user-4"],
    whitelabelId: "wl-1",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "team-2",
    name: "Leões do Mercado",
    description: "Especialistas em vendas consultivas",
    color: "#f59e0b",
    leaderId: "user-5",
    memberIds: ["user-5", "user-6"],
    whitelabelId: "wl-1",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "team-3",
    name: "Tubarões Tech",
    description: "Foco em soluções tecnológicas",
    color: "#10b981",
    leaderId: "user-3",
    memberIds: ["user-3", "user-7"],
    whitelabelId: "wl-2",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
]

// Mock users for teams
export const mockUsersExtended: User[] = [
  ...mockUsers,
  {
    id: "user-4",
    email: "carlos@acme.com",
    name: "Carlos Silva",
    role: "user",
    whitelabelId: "wl-1",
    createdAt: new Date("2024-01-03"),
    updatedAt: new Date("2024-01-03"),
  },
  {
    id: "user-5",
    email: "maria@acme.com",
    name: "Maria Santos",
    role: "user",
    whitelabelId: "wl-1",
    createdAt: new Date("2024-01-04"),
    updatedAt: new Date("2024-01-04"),
  },
  {
    id: "user-6",
    email: "pedro@acme.com",
    name: "Pedro Costa",
    role: "user",
    whitelabelId: "wl-1",
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05"),
  },
  {
    id: "user-7",
    email: "ana@techstart.com",
    name: "Ana Oliveira",
    role: "user",
    whitelabelId: "wl-2",
    createdAt: new Date("2024-01-16"),
    updatedAt: new Date("2024-01-16"),
  },
]

// More deals for team competition
export const mockDealsExtended: Deal[] = [
  ...mockDeals,
  {
    id: "deal-4",
    title: "Cloud Migration Project",
    value: 75000,
    stage: "closed-won",
    contactId: "contact-1",
    whitelabelId: "wl-1",
    assignedTo: "user-4",
    expectedCloseDate: new Date("2024-02-15"),
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-02-15"),
  },
  {
    id: "deal-5",
    title: "Marketing Automation",
    value: 35000,
    stage: "closed-won",
    contactId: "contact-2",
    whitelabelId: "wl-1",
    assignedTo: "user-5",
    expectedCloseDate: new Date("2024-02-20"),
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-02-20"),
  },
  {
    id: "deal-6",
    title: "Security Audit",
    value: 28000,
    stage: "closed-won",
    contactId: "contact-1",
    whitelabelId: "wl-1",
    assignedTo: "user-6",
    expectedCloseDate: new Date("2024-02-25"),
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-02-25"),
  },
]

// Team statistics
export const mockTeamStats: TeamStats[] = [
  {
    teamId: "team-1",
    totalDeals: 3,
    totalRevenue: 125000,
    closedDeals: 2,
    pipelineValue: 50000,
    period: "month",
    periodStart: new Date("2024-02-01"),
    periodEnd: new Date("2024-02-29"),
  },
  {
    teamId: "team-2",
    totalDeals: 2,
    totalRevenue: 63000,
    closedDeals: 2,
    pipelineValue: 25000,
    period: "month",
    periodStart: new Date("2024-02-01"),
    periodEnd: new Date("2024-02-29"),
  },
  {
    teamId: "team-3",
    totalDeals: 1,
    totalRevenue: 12000,
    closedDeals: 1,
    pipelineValue: 0,
    period: "month",
    periodStart: new Date("2024-02-01"),
    periodEnd: new Date("2024-02-29"),
  },
]

// Active competition
export const mockCompetitions: Competition[] = [
  {
    id: "comp-1",
    name: "Batalha de Fevereiro",
    description: "Competição mensal de vendas - quem fecha mais negócios?",
    type: "revenue",
    startDate: new Date("2024-02-01"),
    endDate: new Date("2024-02-29"),
    whitelabelId: "wl-1",
    isActive: true,
    createdAt: new Date("2024-01-25"),
  },
]
